### PR TITLE
Move the staging of input, output, and checkpoint files inside the container

### PR DESCRIPTION
**Pull request by duncan-brown**
Currently pegasus lite stages in the job's container file, input files, and checkpoint files before starting the container. It stages the output files back after the container exits.

This makes jobs less portable as Pegasus relies on executables (e.g. `gfal-copy`) being installed on the job's execute site OS, which the submitting user probably does not control. However, the user does have control over the contents of the container environment that runs the job, in the case of Singularity and Docker container.

This pull request splits up file staging, so that the *container* file (if there is one) is the only file that is staged outside the container itself. All other staging of input, output, and checkpoint files is performed inside the container.

This means that the user can run on sites that e.g. don't have `gfal-copy` installed, as long as they have installed it in their container. If the container is missing `gfal-copy`, etc. then as long as it is in the host OS, then the code will execute fine (the previous behavior).

If the `None` container is used, the behavior of the code is as before.

### CODE REVIEW

**Comment by vahi** [comment]
Our plan for this request
- Tag and Release 4.9.0 as is.
- Then merge these changes into 4.9 branch and get our bamboo tests green
- As part of this we will have change our credential handling to take into account that transfers are happening in the container.
- Also, we need to revisit and make sure symlinking cases work correctly with the change.

**Comment by duncan-brown** [comment]
@vahi I think that the patch https://github.com/duncan-brown/pegasus/commit/d0c95051fbcd2ee0b5f11c00a68992dce5c58b1f is needed so that symlinking works properly for container jobs. I didn't include it in this pull request, but it's an easy fix. Please can you include this before running the 4.9.1 tests?

**Comment by duncan-brown** [comment]
@rynge @vahi I think I understand what the confusion is... Karan enabled symlinking for container jobs if the `symlink:` URI in the PFN is written by the planner. For cases where `pegasus-transfer` has several PFNs that it can select from, you need to pass `--symlink` to `pegasus-transfer` in the pegasus lite script.

Without this patch, I get
```
pegasus-transfer --threads 1 1>&2 << 'eof'
[
 { "type": "transfer",
   "linkage": "input",
   "lfn": "112625/H-H1_LOSC_16_V1-1126256640-4096.gwf",
   "id": 1,
   "src_urls": [
     { "site_label": "orangegrid", "url": "file:///cvmfs/gwosc.osgstorage.org/gwdata/O1/strain.16k/frame.v1/H1/1126170624/H-H1_LOSC_16_V1-1126256640-4096.gwf", "priority": 400, "checkpoint": "false" },
     { "site_label": "orangegrid", "url": "https://www.gw-openscience.org/archive/data/O1_16KHZ/1126170624/H-H1_LOSC_16_V1-1126256640-4096.gwf", "priority": 0, "checkpoint": "false" }
   ],
   "dest_urls": [
     { "site_label": "orangegrid", "url": "file:///srv/112625/H-H1_LOSC_16_V1-1126256640-4096.gwf" }
   ] }
]
```
so `pegasus-transfer` will do a `cp` if the `file` URL is available. With this patch, I get
```
pegasus-transfer --threads 1  --symlink  1>&2 << 'eof'
[
 { "type": "transfer",
   "linkage": "input",
   "lfn": "112625/H-H1_LOSC_16_V1-1126256640-4096.gwf",
   "id": 1,
   "src_urls": [
     { "site_label": "orangegrid", "url": "file:///cvmfs/gwosc.osgstorage.org/gwdata/O1/strain.16k/frame.v1/H1/1126170624/H-H1_LOSC_16_V1-1126256640-4096.gwf", "priority": 400, "checkpoint": "false" },
     { "site_label": "orangegrid", "url": "https://www.gw-openscience.org/archive/data/O1_16KHZ/1126170624/H-H1_LOSC_16_V1-1126256640-4096.gwf", "priority": 0, "checkpoint": "false" }
   ],
   "dest_urls": [
     { "site_label": "orangegrid", "url": "file:///srv/112625/H-H1_LOSC_16_V1-1126256640-4096.gwf" }
   ] }
]
```
so if the `file:` URL is available, `pegasus-transfer` will symlink instead of copying.

**Comment by duncan-brown** [comment]
@vahi hold off merging this... it needs one more fix that I forgot to commit.

**Pull request merged**
