### PR TITLE
unpin dependencies on flask

### PR DESCRIPTION
**Pull request by ahnitz**
The latest release of markupsafe has exposed a side-effect of pinning dependencies on flask, whose old versions also require an old version of jinja2. The old version of jinja2 breaks with the latest markupsafe. This means that at the moment, pegasus-wms can't be installed with pip and used as intended. The most recent version of markupsafe will be installed and thus break. 

See also https://github.com/pallets/flask/issues/4455

### CODE REVIEW

**Comment by mayani** [comment]
1. `pegasus-wms` pip package is not a complete Pegasus install. It contains only the python code.  It is not meant to be used, but is provided for completeness.
2. Removing version bounds is not a good idea, as future releases could be incompatible and break future installs. We added them due to such an issue.
3. The flask ticket you reference mentions the issue has been fixed in `v1.1.4`, which would fall within the bounds of the constraint `Flask>1.1,<1.2`
4. Also, I was able to install it without issue. Can you try in a clean environment or describe what and how you are trying to accomplish?

**Comment by mayani** [comment]
@ahnitz, Closing PR as it seems your use case is served by depending on `pegasus-wms.api` [gwastro/pycbc/pull/3943](https://github.com/gwastro/pycbc/pull/3943)

**Comment by ahnitz** [comment]
@mayani 

1) Can you clarify what the model is for python users to use pegasus? Sure, binary blobs can be installed system-wide, but if we depend on the API and *also* need system isolated python env for our own code, then we need to install the python parts into our own environment. Such strict dependencies from Pegasus then get imposed on any downstream libraries and applications. If Pegasus now has complete isolation from local python code and I've missed it, then yes I see how this would be a non-issue. It is not clear how to enable this though as if I install the pegasus5 rpms followed by creating say a virtualenv testing would indicate that the python parts of pegasus provided by pegasus-wms do indeed have to be reinstalled into one's local virtualenv. 

2) Opinions will clearly vary on this. My experience is that its somewhat unusual practice to pin dependencies with an upper bound in the python ecosystem for python libraries (as opposed to end point applications) exactly because it can result in breakages such as this one. 

3) If you read further you'll find that indeed flask 1.1.4 is not sufficient to address the issue with markupsafe, it only addresses a separate issue with isdangerous. One would need to move to a version of flask that no longer requires jinja2 2.x, but rather 3.x

4) The code installs, but results in a packageset which is incompatible with eachother. The reported error is of the form 

```
ImportError: cannot import name 'soft_unicode' from 'markupsafe'
```

Any code which tries to import this (such as some functions in jinja2) would fail.

**Comment by ahnitz** [comment]
@mayani Just to clarify, I wouldn't consider our temporary change a long-term fix as it still means that if anything downstream of us requires a working flask / jinja2 installation (at least in full) could fail. It really just addressed the immediate problem of our CI continuously failing by avoiding installing parts of pegasus that rely on flask for cases where we ourselves need to use jinja (in our case it is used implicitly by jupyter).

**Comment by mayani** [comment]
@ahnitz 

1. To develop a workflow, model is to depend on `pegasus-wms.api`. However to run the workflow a Pegasus install is required, via RPM, binary tarballs, source install etc.

2. Initially we did not pin down max versions, but at a point we noticed issues with an updated version of SQLAlchemy, so we chose to start pinning down versions. The best we can do is to keep moving the upper bounds after testing during releases.

3. It seems Jinja2 does not pin down the max version, which causes the error. The version constraint is >0.23, but ended up failing on 2.1, which itself makes a case for pinning down versions.

**Comment by mayani** [comment]
@ahnitz 

I am not sure why you refer to the change as "temporary" (may be my earlier reply was after you posted the reply), as the use of `pegasus-wms.api` package is our recommended/advertised approach. If there are downstream dependencies requiring Jijna2, they would need to be addressed in those codebases.

My preferred approach would be to have the issue resolved in MarkupSafe, which I believe you have reported. A workaround until then, would be to add a constraint in pycbc to pin down the version of MarkupSafe to a functioning version.

**Comment by ahnitz** [comment]
@mayani  Sorry, let me clarify. The change we made is fine for the library side and would not be reverted. The problem is that for other tests, we still have to install other pegasus-wms tools to ensure we can actually launch pegasus workflows. The pegasus RPM is not particularly useful for the python parts it provides as we need to run our codes in system-isolated python virtual environments. That's normally fine as the needed python portions of Pegasus can be installed through the pegasus-wms package. This means though that because of the requirements imposed by pegasus-wms, there is no way to have a full software stack that can both run downstream software and be able to run pegasus workflows. It is very possible that version mismatches in python libraries will cause further issues in the future if we every do require library versions that conflict with pegasus in production workflows.

**Pull request closed without merging**
